### PR TITLE
added snake and breakout examples

### PR DESCRIPTION
**Pull request by clsource**

### CODE REVIEW

**Comment by avivbeeri** [comment]
You may want to go through and correct the indentation for both of these examples, which are currently a little inconsistent.

**Comment by clsource** [comment]
I wish automatic formatting was available for wren xd.

**Comment by clsource** [comment]
Another option would be using git submodules to pin all the other examples scattered in github

**Comment by avivbeeri** [comment]
I'm open to that idea. I intend to move the examples in the DOME repo in
here too. And keep them pinned as submodules.

**Comment by clsource** [comment]
ok I will close this and add them as submodules

**Pull request closed without merging**
